name: Resize images

on:
  workflow_run:
    workflows: ["GitHub Pages Hugo"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    name: Github Action Image Resizing
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Resize Images

        # You can change the version as well
        uses: gonzalonaveira/gh-image-resizing@master
        with:
          IMAGES_MAX_WIDTH: "800"
          IMAGES_QUALITY: "90"
          IMAGES_FORMATS: "jpg, jpeg, png" 
          IMAGES_DIRECTORIES: "content/photography"

#      - name: Commit changes
#        uses: EndBug/add-and-commit@v4
#        with:
#          add: 'public/'
#          author_name: "github-actions[bot]"
#          author_email: "github-actions@users.noreply.github.com"
#          message: |
#            Images Reszied by Github action
#            ${{steps.resize-images.outputs.result}}
            
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}