name: Resize images

on:
  workflow_dispatch:    
  workflow_run:
    workflows: ["GitHub Pages Hugo"]
    branches: [main]
    types: 
      - completed

jobs:
  resize-images:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: true

      - name: Build directories list
        id: builddirs
        run: |
          DIRS=$(find content/photography -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) -printf '%h\n' | sort -u | paste -sd, -)
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT

      - name: Debug show dirs
        run: |
          echo "DIRS from step output: ${{ steps.builddirs.outputs.dirs }}"

      - name: Resize images
        uses: gonzalonaveira/gh-image-resizing@master
        with:
          IMAGES_MAX_WIDTH: 1200
          IMAGES_QUALITY: 90
          IMAGES_FORMATS: "jpg,jpeg,png,webp"
          IMAGES_DIRECTORIES: ${{ steps.builddirs.outputs.dirs }}
          IMAGES_SUFFIX: "-resized"
          DEBUG: true

      - name: Commit resized images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/photography/**/*-resized.* || true
          git commit -m "Resize photography images" || echo "No changes to commit"
          git push

